set_property SRC_FILE_INFO {cfile:C:/verilog_matbi/axi_spi_test3/axi_spi_test3.srcs/constrs_1/imports/Oscilloscope/Cora-Z7-07S-Master.xdc rfile:../../../axi_spi_test3.srcs/constrs_1/imports/Oscilloscope/Cora-Z7-07S-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports sclk]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports cs]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports miso]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports mosi]
